### ISSUE TITLE
macOS Theme seems to keep Joplin (arm64) from starting up

### ISSUE THREAD

**Issue by yodahome** [andrejilderda/joplin-macos-native-theme#104] opened 2023-08-09 17:08 UTC
I switched to the arm64 version of Joplin v11.11 and on startup got a blank window with no content and no error messages that I could only close by doing a force quit. I didn't follow up on this, as it worked with the Intel version of the app. With the latest version 12.10 I tried again, same result. So I started turning off some of my plugins and could get Joplin (arm64) to start up again when I turned macOS Theme off (I didn't delete it). I have now checked several other combinations and it's only this plugin that causes startup to break.

I also added this info to an issue on the main Joplin app https://github.com/laurent22/joplin/issues/8622#issuecomment-1671808464 as I don't know whether it's a problem with the plugin or with the main app.

**Comment by MiracleXYZ** [comment] 2023-08-12 16:31
I'm experiencing the same issue too. Sometimes it functions correctly, but other times I only see a blank screen. I'm unsure of the cause.

**Comment by jibedoubleve** [comment] 2024-02-06 21:37
Duplicate of #96

**Closed** 2024-05-12 15:36 UTC
