### ISSUE TITLE
Notebook (folder) icons disapeared after update to v1.5.3

### ISSUE THREAD

**Issue by iAweX** [andrejilderda/joplin-macos-native-theme#137] opened 2024-05-12 17:29 UTC
OS: Debian 12 (bookworm)
Jopplin v2.14.20
macOS theme v1.5.3

Notebook (folder) icons disapeared after update to v1.5.3 from joplin repo

![image](https://github.com/andrejilderda/joplin-macos-native-theme/assets/50710418/e348d75e-e3ec-46f1-a0d6-935fd3a350b6)

**Comment by andrejilderda** [comment] 2024-05-12 17:32
Hmm... interesting. Do you have the icon family set to Phosphor?

<img width="841" alt="image" src="https://github.com/andrejilderda/joplin-macos-native-theme/assets/487182/9edeb8c6-7ea4-41e7-813f-99bf33b4519a">

**Comment by iAweX** [comment] 2024-05-12 17:56
I have both fonts installed and tried to switch between them, but with no success. Before update everything worked fine with both fonts.

**Comment by andrejilderda** [comment] 2024-05-12 21:56
@iAweX Hopefully this is fixed with v.1.5.6. Can you confirm if that's the case?

You should not have to install Phosphor icons by the way, since it comes with the theme.

**Comment by iAweX** [comment] 2024-05-13 06:23
Unfortunately [PR 139](https://github.com/andrejilderda/joplin-macos-native-theme/pull/139) didn't fixed missed icons.
And icons missed when trying to use both fonts.

**Comment by andrejilderda** [comment] 2024-05-13 06:28
I see that you're using an older version of Joplin. Have you tried upgrading to v3?

**Comment by andrejilderda** [comment] 2024-05-13 07:10
Ah got it! Wasn't aware I was using a pre-release. 😅 I just downgraded and can reproduce the issue. Hope to have a fix soon.

**Comment by iAweX** [comment] 2024-05-13 07:22
@andrejilderda, thanks for your macos theme and help. It's Great!

**Comment by andrejilderda** [comment] 2024-05-14 17:26
@iAweX I put up a fix in v1.5.7. Can you check if this solves the issue for you?

**Comment by iAweX** [comment] 2024-05-14 18:36
> @iAweX I put up a fix in v1.5.7. Can you check if this solves the issue for you?

Issue solved. Thanks!

**Closed** 2024-05-29 12:09 UTC
