### ISSUE TITLE
Problems with markdown rendering on MacOS

### ISSUE THREAD

**Issue by pschopen** [andrejilderda/joplin-macos-native-theme#72] opened 2022-05-17 20:56 UTC
Since using the Mac Theme with Joplin I discovered some Problems with markdown rendering that don't show up using the original theme. See the video attached. Rendering is only correct after pressing the button and switching between the modes. And even then the correct rendering is still slightly delayed.

https://user-images.githubusercontent.com/65334274/168908514-b4c8c75b-5ae8-4240-89cd-db83f6a59a41.mov

**Comment by ScriptInfra** [comment] 2022-05-23 22:05
Good catch on this, @pschopen! I am seeing this issue as well running Joplin on Linux. I knew about this issue but assumed it was an issue with the core Joplin app since I exclusively use the MacOS theme.

**Comment by pschopen** [comment] 2022-05-24 20:25
My impression was, that it has something to do with the styling that the theme does to the markdown text. A solution could be to offer only the interface styling and have markdown styling only as an option within extension settings?

**Comment by andrejilderda** [comment] 2022-11-12 08:17
Hi @pschopen , can you check if this is solved after upgrading to the latest version? (1.3.5)

**Comment by andrejilderda** [comment] 2022-12-21 20:43
Thanks for checking this @pschopen & @ScriptInfra . With the newest version (v1.3.9) this should be fixed. Can you confirm if that is the case? If not, feel free to reopen this issue.

**Closed by andrejilderda** 2022-12-21 20:43 UTC

**Comment by ScriptInfra** [comment] 2022-12-21 22:03
@andrejilderda - I am no longer able to reproduce this issue. Thanks so much for fixing this! What a huge quality improvement! I'll report back if I see any issues after further use.

**Comment by andrejilderda** [comment] 2022-12-21 22:08
Great! 🎉

**Comment by pschopen** [comment] 2023-01-11 12:22
> @andrejilderda - I am no longer able to reproduce this issue. Thanks so much for fixing this! What a huge quality improvement! I'll report back if I see any issues after further use.

Same for me. Thank you very much; it makes a big difference!
