### ISSUE TITLE
New issue with Joplin 2.9.17 freezing

### ISSUE THREAD

**Issue by mackiechan4** [andrejilderda/joplin-macos-native-theme#88] opened 2022-12-17 22:14 UTC
Hello. I've noticed that when using the macos theme plugin v1.3.5 with the new version of Joplin 2.9.17, clicking the dropdown arrow next to a folder causes Joplin to freeze/crash. This issue occurs even after reinstalling the plugin and disabling all other plugins, and this issue resolves when I disable the macos theme plugin.

**Comment by andypiper** [comment] 2022-12-21 00:41
I can confirm that I'm seeing the same behaviour and problem, using an M1 Mac with Ventura, and the same versions of the software and the plugin. I've disabled the plugin for now, but I'd love to be able to enable it again!

**Comment by andrejilderda** [comment] 2022-12-21 18:22
That is superweird. I'm on the same platform but can't reproduce the issue with the same version of Joplin. Could it be that a conflict with another plugin is causing the issue, like [here is the case](https://github.com/andrejilderda/joplin-macos-native-theme/issues/87)?

**Comment by jibedoubleve** [comment] 2022-12-21 20:39
Same issue for me.

If I navigate in the tree and I randomly select notebooks it'll eventually freeze the UI. I'm still trying to understand on what event it freezes.

```
Joplin 2.9.17 (prod, darwin)

Client ID: ccb2807a53db48afae96a22577554662
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: a84a8e7
```

**Comment by ScriptInfra** [comment] 2022-12-21 22:09
Could it be related to the number of sub-notebooks, number of notes, or contents of the notes etc?

I am not able to reproduce this issue either, very strange..

Joplin: 2.9.17
macOS theme: 1.3.9
macOS: 13.1

**Comment by mackiechan4** [comment] 2022-12-21 23:24
Good thought, you may be on to something. 
I tried opening a notebook with 7 notes and it worked fine, but when I tried the dropdown arrow on my large notebook containing 50+ notes w/ images, the error occurred again.

**Comment by JetGum** [comment] 2022-12-22 12:02
Had the same problem (sudden freezes, where i had to kill the application) with Joplin 2.9.17 (prod, win32).

This is what I did:

1. I disabled or removed macOS theme extension
2. Deleted all Emojis I added to folders
3. reinstalled macOS theme

Haven't had a freeze for a couple of days so far.
Hope this helps.

**Comment by andrejilderda** [comment] 2022-12-27 20:30
Sorry everyone, but I have to close this issue. While the theme may play a role, I think it isn't causing the actual issue at hand, since the theme is doing very little other than injecting CSS. If you find new hints or you think otherwise, feel free to comment or reopen! Thanks for investigating!

**Closed by andrejilderda** 2022-12-27 20:30 UTC

**Comment by jibedoubleve** [comment] 2023-02-22 10:59
The problem is still there with `Joplin 2.10.6 (prod, darwin)` **without** any plugins

I tested on 
 * Windows 10 (10.0.19045) **and** macOS Ventura 13.0.1
 * Different notebooks configurations

It seems that UI freezes when I expand group of notebooks with emojis
